name: 'Setup Node.js Securely'
description: 'Sets up Node.js environment with caching and security audit checks'
author: 'Algenium Systems'

inputs:
  node-version:
    description: 'Node.js version to install. If not provided, reads from .nvmrc file.'
    required: false
    default: ''
  package-manager:
    description: 'Package manager to use: npm, pnpm, or yarn (default: auto-detect)'
    required: false
    default: 'auto'
  cache-dependency-path:
    description: 'Path to lockfile for cache key computation (package-lock.json, pnpm-lock.yaml, or yarn.lock)'
    required: false
    default: ''
  working-directory:
    description: 'Working directory for package manager commands'
    required: false
    default: '.'
  skip-install:
    description: 'Skip dependency installation (default: false)'
    required: false
    default: 'false'
  skip-audit:
    description: 'Skip security audit step (default: false)'
    required: false
    default: 'false'

outputs:
  node-version:
    description: 'The Node.js version that was installed'
    value: ${{ steps.node-version.outputs.version }}
  package-manager:
    description: 'The detected or configured package manager'
    value: ${{ steps.detect-pm.outputs.package-manager }}
  cache-hit:
    description: 'Whether dependencies were restored from cache'
    value: ${{ steps.setup-node.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Read Node.js version from .nvmrc
      id: nvmrc
      if: inputs.node-version == ''
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -f .nvmrc ]; then
          echo "version=$(cat .nvmrc | tr -d '[:space:]')" >> $GITHUB_OUTPUT
          echo "✓ Read Node.js version from .nvmrc: $(cat .nvmrc | tr -d '[:space:]')"
        else
          echo "::error::No .nvmrc file found and no node-version input provided"
          exit 1
        fi

    - name: Set Node.js version
      id: node-version
      shell: bash
      run: |
        if [ -n "${{ inputs.node-version }}" ]; then
          echo "version=${{ inputs.node-version }}" >> $GITHUB_OUTPUT
          echo "✓ Using Node.js version from input: ${{ inputs.node-version }}"
        else
          echo "version=${{ steps.nvmrc.outputs.version }}" >> $GITHUB_OUTPUT
          echo "✓ Using Node.js version from .nvmrc: ${{ steps.nvmrc.outputs.version }}"
        fi

    - name: Detect package manager
      id: detect-pm
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        PM="${{ inputs.package-manager }}"

        if [ "$PM" = "auto" ]; then
          if [ -f "pnpm-lock.yaml" ]; then
            PM="pnpm"
            LOCKFILE="pnpm-lock.yaml"
          elif [ -f "yarn.lock" ]; then
            PM="yarn"
            LOCKFILE="yarn.lock"
          elif [ -f "package-lock.json" ]; then
            PM="npm"
            LOCKFILE="package-lock.json"
          else
            echo "::warning::No lockfile found, defaulting to npm"
            PM="npm"
            LOCKFILE="package-lock.json"
          fi
        else
          case "$PM" in
            pnpm)
              LOCKFILE="pnpm-lock.yaml"
              ;;
            yarn)
              LOCKFILE="yarn.lock"
              ;;
            npm)
              LOCKFILE="package-lock.json"
              ;;
            *)
              echo "::error::Unknown package manager: $PM"
              exit 1
              ;;
          esac
        fi

        # Use provided cache-dependency-path or build the path from working-directory + lockfile
        if [ -n "${{ inputs.cache-dependency-path }}" ]; then
          CACHE_PATH="${{ inputs.cache-dependency-path }}"
        else
          # Build path relative to repo root
          WORK_DIR="${{ inputs.working-directory }}"
          if [ "$WORK_DIR" = "." ] || [ -z "$WORK_DIR" ]; then
            CACHE_PATH="$LOCKFILE"
          else
            # Remove trailing slash if present
            WORK_DIR="${WORK_DIR%/}"
            CACHE_PATH="${WORK_DIR}/${LOCKFILE}"
          fi
        fi

        echo "package-manager=$PM" >> $GITHUB_OUTPUT
        echo "lockfile=$LOCKFILE" >> $GITHUB_OUTPUT
        echo "cache-path=$CACHE_PATH" >> $GITHUB_OUTPUT
        echo "✓ Detected package manager: $PM"
        echo "✓ Using lockfile: $LOCKFILE"
        echo "✓ Cache path: $CACHE_PATH"

    - name: Setup pnpm
      if: steps.detect-pm.outputs.package-manager == 'pnpm'
      uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.node-version.outputs.version }}
        cache: ${{ steps.detect-pm.outputs.package-manager }}
        cache-dependency-path: ${{ steps.detect-pm.outputs.cache-path }}

    - name: Install dependencies
      if: inputs.skip-install != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "::group::Installing dependencies with ${{ steps.detect-pm.outputs.package-manager }}"

        case "${{ steps.detect-pm.outputs.package-manager }}" in
          pnpm)
            echo "Running: pnpm install --frozen-lockfile"
            pnpm install --frozen-lockfile
            ;;
          yarn)
            echo "Running: yarn install --frozen-lockfile"
            yarn install --frozen-lockfile
            ;;
          npm)
            echo "Running: npm ci --ignore-scripts"
            npm ci --ignore-scripts
            ;;
        esac

        echo "✓ Dependencies installed successfully"
        echo "::endgroup::"

    - name: Run security audit
      if: inputs.skip-audit != 'true' && inputs.skip-install != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: true
      run: |
        echo "::group::Running security audit"
        echo "Running security audit with ${{ steps.detect-pm.outputs.package-manager }} (non-blocking)..."

        case "${{ steps.detect-pm.outputs.package-manager }}" in
          pnpm)
            if pnpm audit --audit-level=moderate; then
              echo "✓ No vulnerabilities found"
            else
              echo "::warning::pnpm audit found vulnerabilities. Please review and update dependencies."
            fi
            ;;
          yarn)
            if yarn audit --level moderate; then
              echo "✓ No vulnerabilities found"
            else
              echo "::warning::yarn audit found vulnerabilities. Please review and update dependencies."
            fi
            ;;
          npm)
            if npm audit --audit-level=moderate; then
              echo "✓ No vulnerabilities found"
            else
              echo "::warning::npm audit found vulnerabilities. Please review and update dependencies."
            fi
            ;;
        esac

        echo "::endgroup::"
