name: "Workflow Version Banner"
description: "Displays the workflow name and version for tracking purposes"
author: "Algenium Systems"

inputs:
  workflow_name:
    description: "Name of the workflow to display"
    required: true

runs:
  using: "composite"
  steps:
    - name: Display Workflow Version
      shell: bash
      run: |
        WORKFLOW_NAME="${{ inputs.workflow_name }}"

        # Read version from package.json at repo root
        PACKAGE_JSON_PATH="${GITHUB_ACTION_PATH}/../../package.json"

        if [ -f "$PACKAGE_JSON_PATH" ]; then
          VERSION=$(node -p "require('$PACKAGE_JSON_PATH').version")
          VERSION_STRING="v${VERSION}"
        else
          VERSION_STRING="unknown"
        fi

        # Console output
        echo "🔄 Workflow: ${WORKFLOW_NAME} | Version: ${VERSION_STRING}"

        # GitHub Actions summary output
        echo "## 🔄 ${WORKFLOW_NAME} | ${VERSION_STRING}" >> "$GITHUB_STEP_SUMMARY"
