name: "Test Template"
description: "Tests template packaging and provision regression"

inputs:
  working_directory:
    description: "Directory containing the template"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Display Action Version
      uses: ../../action-version-banner
      with:
        action_name: "Test Template"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: pnpm install --frozen-lockfile

    - name: Copy transform utility to template
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        echo "📋 Copying transform utility..."
        mkdir -p scripts
        cp "${{ github.action_path }}/transformTemplateToApp.ts" scripts/transformTemplateToApp.ts
        echo "✅ Transform utility copied"

    - name: Get template info
      id: template-info
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set -euo pipefail

        if [ ! -f "package.json" ]; then
          echo "❌ package.json not found"
          exit 1
        fi

        TEMPLATE_NAME=$(jq -r '.name' package.json)
        TEMPLATE_VERSION=$(jq -r '.version' package.json)
        TEMPLATE_TYPE=$(jq -r '.algtools.kind // "bff"' package.json)

        # Normalize template type
        if [ "${TEMPLATE_TYPE}" != "web" ] && [ "${TEMPLATE_TYPE}" != "core" ]; then
          TEMPLATE_TYPE="bff"
        fi

        echo "template_name=${TEMPLATE_NAME}" >> "$GITHUB_OUTPUT"
        echo "template_version=${TEMPLATE_VERSION}" >> "$GITHUB_OUTPUT"
        echo "template_type=${TEMPLATE_TYPE}" >> "$GITHUB_OUTPUT"

        echo "📋 Template info:"
        echo "  Name: ${TEMPLATE_NAME}"
        echo "  Version: ${TEMPLATE_VERSION}"
        echo "  Type: ${TEMPLATE_TYPE}"

    - name: Run template pack utility
      uses: algtools/actions/.github/actions/template-pack-utility@main
      with:
        working_directory: ${{ inputs.working_directory }}
        template_name: ${{ steps.template-info.outputs.template_name }}
        template_type: ${{ steps.template-info.outputs.template_type }}

    - name: Create tarball
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set -euo pipefail

        BUILD_DIR="${{ inputs.working_directory }}/.template-build"
        DIST_DIR="${{ inputs.working_directory }}/template-dist"
        TARBALL_NAME="${{ steps.template-info.outputs.template_name }}-v${{ steps.template-info.outputs.template_version }}.tgz"
        TARBALL_PATH="template-dist/${TARBALL_NAME}"

        if [ ! -d "${BUILD_DIR}" ]; then
          echo "❌ Build directory not found: ${BUILD_DIR}"
          exit 1
        fi

        # Create dist directory
        mkdir -p "${DIST_DIR}"

        # Create tarball from build directory
        cd "${BUILD_DIR}"
        tar -czf "../${TARBALL_PATH}" .

        echo "✅ Created tarball: ${TARBALL_NAME}"

    - name: Run template packaging tests
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        echo "📦 Running template packaging tests..."
        if [ -f "package.json" ]; then
          # Check if test:template-packaging script exists
          if jq -e '.scripts["test:template-packaging"]' package.json > /dev/null; then
            pnpm run test:template-packaging
          else
            echo "⚠️  test:template-packaging script not found, skipping..."
          fi
        fi

    - name: Extract and validate template structure
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set -euo pipefail

        # Find latest tarball
        if [ ! -d template-dist ] || [ -z "$(ls -A template-dist/*.tgz 2>/dev/null)" ]; then
          echo "❌ No tarball found in template-dist/"
          exit 1
        fi

        TARBALL=$(ls -t template-dist/*.tgz | head -n 1)
        echo "📦 Found tarball: ${TARBALL}"

        # Extract
        mkdir -p .test-extract
        tar -xzf "$TARBALL" -C .test-extract

        # Find extracted directory - check if package.json is at root or in subdirectory
        if [ -f .test-extract/package.json ]; then
          EXTRACTED_DIR=".test-extract"
        else
          EXTRACTED_DIR=$(find .test-extract -mindepth 1 -maxdepth 1 -type d -exec test -f {}/package.json \; -print | head -n 1)
        fi

        if [ -z "$EXTRACTED_DIR" ]; then
          echo "❌ Could not find extracted directory with package.json"
          exit 1
        fi

        echo "✅ Extracted to: ${EXTRACTED_DIR}"

        # Run validation using the action's validation script
        echo "🔍 Running validation..."
        npx tsx "${{ github.action_path }}/validateProvisionedApp.ts" "$EXTRACTED_DIR"

    - name: Verify workflows are correct
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set -euo pipefail

        # Find extracted directory
        if [ -f .test-extract/package.json ]; then
          EXTRACTED_DIR=".test-extract"
        else
          EXTRACTED_DIR=$(find .test-extract -mindepth 1 -maxdepth 1 -type d -exec test -f {}/package.json \; -print | head -n 1)
        fi

        if [ -z "$EXTRACTED_DIR" ]; then
          echo "❌ Could not find extracted directory with package.json"
          exit 1
        fi

        echo "🔍 Verifying workflow configuration..."

        # Check release-app.yml exists
        if [ ! -f "$EXTRACTED_DIR/.github/workflows/release-app.yml" ]; then
          echo "❌ Missing release-app.yml"
          exit 1
        fi

        # Check template workflows are excluded
        if [ -f "$EXTRACTED_DIR/.github/workflows/release-template.yml" ]; then
          echo "❌ Should NOT have release-template.yml"
          exit 1
        fi

        if [ -f "$EXTRACTED_DIR/.github/workflows/retry-release.yml" ]; then
          echo "❌ Should NOT have retry-release.yml"
          exit 1
        fi

        if [ -f "$EXTRACTED_DIR/.github/workflows/provision-template.yml" ]; then
          echo "❌ Should NOT have provision-template.yml"
          exit 1
        fi

        echo "✅ Workflow validation passed"

    - name: Cleanup
      if: always()
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        rm -rf .test-extract || true
        rm -f scripts/transformTemplateToApp.ts || true
        echo "✅ Cleanup complete"
