#!/usr/bin/env bash
set -euo pipefail

# generate-pr-description.sh
# Generates comprehensive PR description

FROM_VERSION="$1"
TO_VERSION="$2"
METADATA_FILE="$3"
APPLICATION_REPORT="$4"
TEMPLATE_NAME="$5"

# Read data
versions_applied=$(jq -r '.applied' "$APPLICATION_REPORT")
files_changed=$(jq -r '.files_changed' "$APPLICATION_REPORT")
diffs_count=$(jq 'length' "$METADATA_FILE")

# Generate PR body
cat << EOF
# 🔄 Template Update: \`$FROM_VERSION\` → \`$TO_VERSION\`

## 📊 Update Summary

This PR updates the **$TEMPLATE_NAME** template with changes from **$diffs_count intermediate version(s)**.

| Metric              | Value |
| ------------------- | ----- |
| 📦 Versions Applied | $versions_applied / $diffs_count |
| 📝 Files Changed    | $files_changed |

## 📋 Version-by-Version Changes

EOF

# Add details for each version
for i in $(seq 0 $((diffs_count - 1))); do
  diff_info=$(jq ".[$i]" "$METADATA_FILE")

  to_version=$(echo "$diff_info" | jq -r '.to_version')
  from_version=$(echo "$diff_info" | jq -r '.from_version')
  files_count=$(echo "$diff_info" | jq -r '.files_changed')
  commits=$(echo "$diff_info" | jq -r '.commits')
  release_info=$(echo "$diff_info" | jq -r '.release_info')

  release_name=$(echo "$release_info" | jq -r '.name // .tag_name')
  release_url=$(echo "$release_info" | jq -r '.html_url')
  release_body=$(echo "$release_info" | jq -r '.body // "No release notes available"' | head -n 10)

  cat << EOF
<details>
<summary>

### ✅ \`$to_version\` - $release_name

</summary>

📊 **Stats:**
- $files_count file(s) changed
- $commits commit(s)

🔗 [View Release]($release_url)

#### Release Notes

$release_body

</details>

EOF
done

# Add review checklist
cat << EOF

## ✅ Review Checklist

- [ ] Review changes for any conflicts or issues
- [ ] Check that custom configurations are preserved
- [ ] Test the application locally
- [ ] Verify all workflows still function correctly
- [ ] Check for any breaking changes in release notes

## 🚀 Deployment

After merging this PR:
1. The changes will be automatically deployed to the dev environment
2. Test thoroughly in dev before promoting to QA
3. Review any migration notes in the version release notes above

---

**Note:** This PR was automatically generated by the template update action.
Files like \`package.json\` and \`wrangler.jsonc\` have been smart-merged to preserve your custom configurations.
EOF
