name: "Copy Transform Utility"
description: "Copies transformTemplateToApp.ts utility to template scripts directory"

inputs:
  working_directory:
    description: "Directory containing the template"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Copy transform utility
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        echo "📋 Copying transform utility..."
        mkdir -p scripts
        cp "${{ github.action_path }}/transformTemplateToApp.ts" scripts/transformTemplateToApp.ts
        echo "✅ Transform utility copied"
