name: "Template Pack Utility"
description: "Wraps, tokenizes, transforms, and prepares template for packaging"
inputs:
  working_directory:
    description: "Directory containing the template"
    required: true
  template_name:
    description: "Name of the template (e.g., bff-template)"
    required: true
  template_type:
    description: "Type of template ('web', 'core', or 'bff')"
    required: false
    default: "bff"
outputs:
  build_dir:
    description: "Path to build directory"
    value: ${{ steps.pack.outputs.build_dir }}
runs:
  using: "composite"
  steps:
    - name: Display Action Version
      shell: bash
      run: |
        ACTION_NAME="Template Pack Utility"
        # Get the repo root by going up 3 levels from GITHUB_ACTION_PATH
        REPO_ROOT=$(cd "${GITHUB_ACTION_PATH}/../../.." && pwd)
        PACKAGE_JSON_PATH="${REPO_ROOT}/package.json"

        if [ -f "$PACKAGE_JSON_PATH" ]; then
          VERSION=$(node -p "require('$PACKAGE_JSON_PATH').version")
          VERSION_STRING="v${VERSION}"
        else
          VERSION_STRING="unknown"
        fi

        echo "🔧 Action: ${ACTION_NAME} | Version: ${VERSION_STRING}"
        echo "## 🔧 ${ACTION_NAME} | ${VERSION_STRING}" >> "$GITHUB_STEP_SUMMARY"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: pnpm install --frozen-lockfile

    - name: Copy template pack utility
      shell: bash
      run: |
        mkdir -p "${{ inputs.working_directory }}/.github/actions/template-pack-utility"
        # Copy all files from action directory
        cp -r "${{ github.action_path }}"/* "${{ inputs.working_directory }}/.github/actions/template-pack-utility/" 2>/dev/null || true
        # Ensure action.yml is not copied (it's not needed)
        rm -f "${{ inputs.working_directory }}/.github/actions/template-pack-utility/action.yml" 2>/dev/null || true

    - name: Install js-yaml for dependabot config updates
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        UTILITY_DIR="${{ inputs.working_directory }}/.github/actions/template-pack-utility"
        cd "${UTILITY_DIR}"
        # Create a minimal package.json if it doesn't exist (required for pnpm)
        if [ ! -f "package.json" ]; then
          echo '{"name": "template-pack-utility", "version": "1.0.0"}' > package.json
        fi
        pnpm add js-yaml@^4.1.0

    - name: Run template packaging
      id: pack
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        BUILD_DIR="${{ inputs.working_directory }}/.template-build"
        echo "build_dir=${BUILD_DIR}" >> "$GITHUB_OUTPUT"
        UTILITY_DIR="${{ inputs.working_directory }}/.github/actions/template-pack-utility"
        # Use absolute path for template root to avoid path resolution issues
        TEMPLATE_ROOT="$(cd "${{ inputs.working_directory }}" && pwd)"
        cd "${UTILITY_DIR}"
        npx tsx index.ts "${TEMPLATE_ROOT}" "${{ inputs.template_name }}" "${{ inputs.template_type }}"
