name: "Bump Version"
description: "Automatically bump version using semantic-release"
inputs:
  github_token:
    description: "GitHub token for authentication"
    required: true
  working_directory:
    description: "Directory containing package.json"
    required: false
    default: "."
  dry_run:
    description: "Run in dry-run mode"
    required: false
    default: "false"
outputs:
  new_version:
    description: "New version number"
    value: ${{ steps.semantic.outputs.new_release_version }}
  new_release_published:
    description: "Whether a new release was published"
    value: ${{ steps.semantic.outputs.new_release_published }}
runs:
  using: "composite"
  steps:
    - name: Display Action Version
      uses: ../../action-version-banner
      with:
        action_name: "Bump Version"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        registry-url: https://npm.pkg.github.com
        scope: "@algtools"

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Install project dependencies
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.github_token }}
      run: pnpm install --frozen-lockfile

    - name: Install semantic-release
      shell: bash
      run: |
        npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/exec

    - name: Run Semantic Release
      id: semantic
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        HUSKY: 0
      run: npx semantic-release ${{ inputs.dry_run == 'true' && '--dry-run' || '' }}
