name: "Update Template Manifest"
description: "Updates .template-manifest.json with current version and fresh checksums"
inputs:
  working_directory:
    description: "Directory containing the template"
    required: true
  github_token:
    description: "GitHub token for committing changes"
    required: true
runs:
  using: "composite"
  steps:
    - name: Display Action Version
      shell: bash
      run: |
        ACTION_NAME="Update Template Manifest"
        # Get the repo root by going up 3 levels from GITHUB_ACTION_PATH
        REPO_ROOT=$(cd "${GITHUB_ACTION_PATH}/../../.." && pwd)
        PACKAGE_JSON_PATH="${REPO_ROOT}/package.json"

        if [ -f "$PACKAGE_JSON_PATH" ]; then
          VERSION=$(node -p "require('$PACKAGE_JSON_PATH').version")
          VERSION_STRING="v${VERSION}"
        else
          VERSION_STRING="unknown"
        fi

        echo "🔧 Action: ${ACTION_NAME} | Version: ${VERSION_STRING}"
        echo "## 🔧 ${ACTION_NAME} | ${VERSION_STRING}" >> "$GITHUB_STEP_SUMMARY"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Install dependencies for manifest update
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        if [ ! -d "node_modules" ]; then
          npm install
        fi

    - name: Update manifest with fresh checksums
      shell: bash
      run: |
        set -euo pipefail

        echo "🔄 Regenerating template manifest..."

        # Resolve absolute path to template directory
        TEMPLATE_DIR="$(cd "${{ inputs.working_directory }}" && pwd)"
        echo "📁 Template directory: ${TEMPLATE_DIR}"

        # Run the manifest update script using npx from the action directory
        cd "${{ github.action_path }}"
        npx tsx ./updateManifest.ts "${TEMPLATE_DIR}"

    - name: Commit updated manifest
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        set -euo pipefail

        MANIFEST_FILE=".template-manifest.json"

        # Configure git
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Check if there are changes
        if git diff --quiet "${MANIFEST_FILE}"; then
          echo "✓ No changes to manifest"
        else
          echo "📝 Committing updated manifest..."
          git add "${MANIFEST_FILE}"
          git commit -m "fix: update template manifest checksums [skip ci]" --no-verify

          # Pull latest changes with rebase, auto-resolving conflicts by keeping our version
          echo "🔄 Pulling latest changes..."
          if ! git pull --rebase origin "$(git branch --show-current)"; then
            echo "⚠️  Rebase conflict detected, resolving automatically..."

            # During rebase, --theirs means our commit being applied (the complete manifest update)
            git checkout --theirs "${MANIFEST_FILE}"
            git add "${MANIFEST_FILE}"

            # Continue the rebase with a dummy editor to avoid interactive prompt
            GIT_EDITOR=true git rebase --continue

            echo "✓ Conflict resolved automatically"
          fi

          echo "📤 Pushing changes..."
          git push
          echo "✅ Manifest committed and pushed"
        fi
