name: "Package Template"
description: "Wraps, tokenizes, transforms, and packages a template into a tarball"
inputs:
  working_directory:
    description: "Directory containing the template"
    required: true
  template_name:
    description: "Name of the template (e.g., bff-template)"
    required: true
  version:
    description: "Version to package"
    required: true
  template_type:
    description: "Type of template ('web', 'core', or 'bff')"
    required: false
    default: "bff"
outputs:
  tarball_path:
    description: "Path to generated tarball"
    value: ${{ steps.pack.outputs.tarball_path }}
  tarball_name:
    description: "Name of generated tarball"
    value: ${{ steps.pack.outputs.tarball_name }}
runs:
  using: "composite"
  steps:
    - name: Run template pack utility
      uses: algtools/actions/.github/actions/template-pack-utility@main
      with:
        working_directory: ${{ inputs.working_directory }}
        template_name: ${{ inputs.template_name }}
        template_type: ${{ inputs.template_type }}

    - name: Format generated files in build directory
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        echo "ðŸŽ¨ Formatting files in build directory..."
        BUILD_DIR="./.template-build"

        if [ -d "${BUILD_DIR}" ]; then
          # Copy prettier config to build directory
          if [ -f ".prettierrc.cjs" ]; then
            cp .prettierrc.cjs "${BUILD_DIR}/.prettierrc.cjs"
            echo "  âœ“ Copied prettier config"
          fi
          if [ -f ".prettierignore" ]; then
            cp .prettierignore "${BUILD_DIR}/.prettierignore"
            echo "  âœ“ Copied prettier ignore"
          fi

          # Run prettier FROM inside the build directory
          echo "  ðŸ”§ Running prettier on all files..."
          cd "${BUILD_DIR}"
          pnpm exec prettier --write . --log-level=warn || {
            echo "  âš ï¸  Prettier encountered issues, but continuing..."
          }
          cd ..

          echo "  âœ“ Prettier config will be included in package for consistency"
          echo "âœ… Build directory formatted"
        else
          echo "âš ï¸  Build directory not found, skipping formatting"
        fi

    - name: Create tarball
      id: pack
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set -euo pipefail

        BUILD_DIR=".template-build"
        DIST_DIR="template-dist"
        TARBALL_NAME="${{ inputs.template_name }}-v${{ inputs.version }}.tgz"
        TARBALL_PATH="${DIST_DIR}/${TARBALL_NAME}"

        # Create dist directory
        mkdir -p "${DIST_DIR}"

        # Create tarball with 'package' parent directory (npm convention)
        # The provision script expects files in extracted/package/
        tar -czf "${TARBALL_PATH}" -C "${BUILD_DIR}" --transform 's,^\.,package,' .

        echo "tarball_path=${TARBALL_PATH}" >> $GITHUB_OUTPUT
        echo "tarball_name=${TARBALL_NAME}" >> $GITHUB_OUTPUT
        echo "âœ… Created tarball: ${TARBALL_NAME}"
