name: "Package Template"
description: "Wraps, tokenizes, transforms, and packages a template into a tarball"
inputs:
  working_directory:
    description: "Directory containing the template"
    required: true
  template_name:
    description: "Name of the template (e.g., bff-template)"
    required: true
  version:
    description: "Version to package"
    required: true
  template_type:
    description: "Type of template ('web', 'core', or 'bff')"
    required: false
    default: "bff"
outputs:
  tarball_path:
    description: "Path to generated tarball"
    value: ${{ steps.pack.outputs.tarball_path }}
  tarball_name:
    description: "Name of generated tarball"
    value: ${{ steps.pack.outputs.tarball_name }}
runs:
  using: "composite"
  steps:
    - name: Display Action Version
      shell: bash
      run: |
        ACTION_NAME="Package Template"
        # Get the repo root by going up 3 levels from GITHUB_ACTION_PATH
        REPO_ROOT=$(cd "${GITHUB_ACTION_PATH}/../../.." && pwd)
        PACKAGE_JSON_PATH="${REPO_ROOT}/package.json"

        if [ -f "$PACKAGE_JSON_PATH" ]; then
          VERSION=$(node -p "require('$PACKAGE_JSON_PATH').version")
          VERSION_STRING="v${VERSION}"
        else
          VERSION_STRING="unknown"
        fi

        echo "🔧 Action: ${ACTION_NAME} | Version: ${VERSION_STRING}"
        echo "## 🔧 ${ACTION_NAME} | ${VERSION_STRING}" >> "$GITHUB_STEP_SUMMARY"

    - name: Run template pack utility
      uses: algtools/actions/.github/actions/template-pack-utility@main
      with:
        working_directory: ${{ inputs.working_directory }}
        template_name: ${{ inputs.template_name }}
        template_type: ${{ inputs.template_type }}

    - name: Create tarball
      id: pack
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set -euo pipefail

        BUILD_DIR=".template-build"
        DIST_DIR="template-dist"
        TARBALL_NAME="${{ inputs.template_name }}-v${{ inputs.version }}.tgz"
        TARBALL_PATH="${DIST_DIR}/${TARBALL_NAME}"

        # Create dist directory
        mkdir -p "${DIST_DIR}"

        # Create tarball with 'package' parent directory (npm convention)
        # The provision script expects files in extracted/package/
        tar -czf "${TARBALL_PATH}" -C "${BUILD_DIR}" --transform 's,^\.,package,' .

        echo "tarball_path=${TARBALL_PATH}" >> $GITHUB_OUTPUT
        echo "tarball_name=${TARBALL_NAME}" >> $GITHUB_OUTPUT
        echo "✅ Created tarball: ${TARBALL_NAME}"
