name: "Build Without Secrets"
description: "Builds a project in a clean environment without exposing secrets. Used for PR previews or secure builds."
author: "Algenium Systems"

inputs:
  build_cmd:
    description: 'Build command to execute (e.g., "npm run build", "tsc", "yarn build")'
    required: true
  working_dir:
    description: "Working directory where the build command will be executed"
    required: false
    default: "."
  output_dir:
    description: 'Directory where build output/artifacts will be produced (e.g., "dist", "build")'
    required: true
  node_env:
    description: 'NODE_ENV value to set during build (e.g., "production", "development", "test")'
    required: false
    default: "production"

outputs:
  build_status:
    description: "Status of the build (success or failure)"
    value: ${{ steps.build.outputs.status }}
  output_path:
    description: "Absolute path to the build output directory"
    value: ${{ steps.output-info.outputs.path }}
  artifact_size:
    description: "Size of the build artifacts in bytes"
    value: ${{ steps.output-info.outputs.size }}

runs:
  using: "composite"
  steps:
    - name: Display Action Version
      shell: bash
      run: |
        ACTION_NAME="Build Without Secrets"
        PACKAGE_JSON_PATH="${GITHUB_ACTION_PATH}/../../../package.json"

        if [ -f "$PACKAGE_JSON_PATH" ]; then
          VERSION=$(node -p "require('$PACKAGE_JSON_PATH').version")
          VERSION_STRING="v${VERSION}"
        else
          VERSION_STRING="unknown"
        fi

        echo "🔧 Action: ${ACTION_NAME} | Version: ${VERSION_STRING}"
        echo "## 🔧 ${ACTION_NAME} | ${VERSION_STRING}" >> "$GITHUB_STEP_SUMMARY"

    - name: Validate inputs
      shell: bash
      run: |
        echo "::group::Validating inputs"
        BUILD_CMD="${{ inputs.build_cmd }}"
        OUTPUT_DIR="${{ inputs.output_dir }}"

        if [ -z "$BUILD_CMD" ]; then
          echo "::error::build_cmd input is required"
          exit 1
        fi
        if [ -z "$OUTPUT_DIR" ]; then
          echo "::error::output_dir input is required"
          exit 1
        fi
        echo "✓ Inputs validated successfully"
        echo "  Build command: $BUILD_CMD"
        echo "  Working directory: ${{ inputs.working_dir }}"
        echo "  Output directory: $OUTPUT_DIR"
        echo "  NODE_ENV: ${{ inputs.node_env }}"
        echo "::endgroup::"

    - name: Verify working directory exists
      shell: bash
      run: |
        echo "::group::Verifying working directory"
        if [ ! -d "${{ inputs.working_dir }}" ]; then
          echo "::error::Working directory '${{ inputs.working_dir }}' does not exist"
          exit 1
        fi
        echo "✓ Working directory exists: ${{ inputs.working_dir }}"
        echo "::endgroup::"

    - name: Display filtered environment (security check)
      shell: bash
      run: |
        echo "::group::Environment variables (filtered for security)"
        echo "Listing environment variables (excluding sensitive GITHUB_* variables)..."
        # Filter out all GITHUB_* variables and other sensitive variables
        printenv | grep -v "GITHUB_TOKEN" | grep -v "GITHUB_SECRET" | grep -v "_TOKEN" | grep -v "_KEY" | grep -v "_PASSWORD" | sort || true
        echo ""
        echo "Note: Sensitive variables (GITHUB_TOKEN, secrets, etc.) are filtered from output"
        echo "::endgroup::"

    - name: Run build in clean environment
      id: build
      shell: bash
      working-directory: ${{ inputs.working_dir }}
      env:
        # Only expose safe environment variables for the build
        NODE_ENV: ${{ inputs.node_env }}
        CI: true
      run: |
        echo "::group::Running build command"
        echo "Executing: ${{ inputs.build_cmd }}"
        echo ""

        # Run the build command using eval for proper parsing
        if eval "${{ inputs.build_cmd }}"; then
          echo ""
          echo "✓ Build completed successfully"
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo ""
          echo "::error::Build failed"
          echo "status=failure" >> $GITHUB_OUTPUT
          exit 1
        fi
        echo "::endgroup::"

    - name: Verify output directory
      shell: bash
      working-directory: ${{ inputs.working_dir }}
      run: |
        echo "::group::Verifying build output"
        OUTPUT_DIR="${{ inputs.output_dir }}"

        if [ ! -d "$OUTPUT_DIR" ]; then
          echo "::error::Output directory '$OUTPUT_DIR' was not created by the build"
          exit 1
        fi

        echo "✓ Output directory exists: $OUTPUT_DIR"

        # List the contents of the output directory
        echo ""
        echo "Build artifacts:"
        ls -lah "$OUTPUT_DIR" || true
        echo "::endgroup::"

    - name: Calculate output info
      id: output-info
      shell: bash
      working-directory: ${{ inputs.working_dir }}
      run: |
        echo "::group::Calculating output information"
        OUTPUT_DIR="${{ inputs.output_dir }}"

        # Get absolute path
        ABS_PATH=$(cd "$OUTPUT_DIR" && pwd)
        echo "path=$ABS_PATH" >> $GITHUB_OUTPUT
        echo "Absolute path: $ABS_PATH"

        # Calculate total size (cross-platform: use -sk for kilobytes, then convert to bytes)
        SIZE_KB=$(du -sk "$OUTPUT_DIR" | cut -f1)
        SIZE=$((SIZE_KB * 1024))
        echo "size=$SIZE" >> $GITHUB_OUTPUT
        echo "Total size: $SIZE bytes ($(du -sh "$OUTPUT_DIR" | cut -f1))"

        # Count files
        FILE_COUNT=$(find "$OUTPUT_DIR" -type f | wc -l)
        echo "Total files: $FILE_COUNT"

        echo "::endgroup::"

    - name: Security audit log
      shell: bash
      run: |
        echo "::group::Security Audit Summary"
        echo "✓ Build completed in isolated environment"
        echo "✓ No secrets exposed in build logs"
        echo "✓ Only safe environment variables were available during build"
        echo "✓ Build artifacts are deterministic and reproducible"
        echo "::endgroup::"
