name: "Update Deployment Status"
description: "Creates and updates GitHub Deployment status for environment deployments and PR previews"
author: "Algenium Systems"

inputs:
  environment:
    description: 'Environment name (e.g., "dev", "qa", "production", "preview-123")'
    required: true
  state:
    description: "Deployment state: pending, in_progress, success, failure, error, inactive"
    required: true
  deployment_url:
    description: "URL where the deployment is accessible (required for success state)"
    required: false
    default: ""
  description:
    description: "Short description of the deployment status"
    required: false
    default: ""
  github_token:
    description: "GitHub token for API access (default: github.token)"
    required: false
    default: ${{ github.token }}
  auto_inactive:
    description: "Automatically mark previous deployments as inactive when creating a new one"
    required: false
    default: "true"

outputs:
  deployment_id:
    description: "ID of the created/updated deployment"
    value: ${{ steps.create-deployment.outputs.deployment_id || steps.update-deployment.outputs.deployment_id }}
  deployment_status_id:
    description: "ID of the deployment status"
    value: ${{ steps.create-status.outputs.status_id }}
  deployment_url:
    description: "URL of the deployment"
    value: ${{ inputs.deployment_url }}

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        echo "::group::Validating deployment inputs"

        if [ -z "${{ inputs.environment }}" ]; then
          echo "::error::environment input is required"
          exit 1
        fi

        if [ -z "${{ inputs.state }}" ]; then
          echo "::error::state input is required"
          exit 1
        fi

        # Validate state value
        case "${{ inputs.state }}" in
          pending|in_progress|success|failure|error|inactive)
            echo "✓ Valid state: ${{ inputs.state }}"
            ;;
          *)
            echo "::error::Invalid state '${{ inputs.state }}'. Must be one of: pending, in_progress, success, failure, error, inactive"
            exit 1
            ;;
        esac

        # Warn if success state without URL
        if [ "${{ inputs.state }}" = "success" ] && [ -z "${{ inputs.deployment_url }}" ]; then
          echo "::warning::deployment_url is recommended for success state"
        fi

        echo "✓ Inputs validated successfully"
        echo "  Environment: ${{ inputs.environment }}"
        echo "  State: ${{ inputs.state }}"
        echo "::endgroup::"

    - name: Create or get deployment
      id: create-deployment
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        echo "::group::Managing GitHub Deployment"

        # Check if we're updating an existing deployment or creating a new one
        # For pending/in_progress states, we create a new deployment
        # For success/failure/error states, we look for an existing deployment

        if [ "${{ inputs.state }}" = "pending" ] || [ "${{ inputs.state }}" = "in_progress" ]; then
          echo "Creating new deployment for environment: ${{ inputs.environment }}"

          # Create deployment using GitHub CLI
          DEPLOYMENT_ID=$(gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/deployments \
            -f ref='${{ github.sha }}' \
            -f environment='${{ inputs.environment }}' \
            -f auto_merge=false \
            -f required_contexts='[]' \
            --jq '.id')

          echo "deployment_id=$DEPLOYMENT_ID" >> $GITHUB_OUTPUT
          echo "✓ Created deployment ID: $DEPLOYMENT_ID"
        else
          echo "Looking for existing deployment..."

          # Get the most recent deployment for this environment and ref
          DEPLOYMENT_ID=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${{ github.repository }}/deployments?environment=${{ inputs.environment }}&sha=${{ github.sha }}" \
            --jq '.[0].id // empty')

          if [ -z "$DEPLOYMENT_ID" ]; then
            echo "::warning::No existing deployment found, creating new one"
            DEPLOYMENT_ID=$(gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/${{ github.repository }}/deployments \
              -f ref='${{ github.sha }}' \
              -f environment='${{ inputs.environment }}' \
              -f auto_merge=false \
              -f required_contexts='[]' \
              --jq '.id')
          fi

          echo "deployment_id=$DEPLOYMENT_ID" >> $GITHUB_OUTPUT
          echo "✓ Using deployment ID: $DEPLOYMENT_ID"
        fi

        echo "::endgroup::"

    - name: Mark previous deployments as inactive
      if: inputs.auto_inactive == 'true' && inputs.state == 'success'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        echo "::group::Marking previous deployments as inactive"

        # Get all active deployments for this environment (excluding current)
        PREV_DEPLOYMENTS=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/${{ github.repository }}/deployments?environment=${{ inputs.environment }}" \
          --jq '.[] | select(.id != ${{ steps.create-deployment.outputs.deployment_id }}) | .id')

        if [ -n "$PREV_DEPLOYMENTS" ]; then
          echo "Found previous deployments to mark as inactive"
          for DEPLOY_ID in $PREV_DEPLOYMENTS; do
            echo "Marking deployment $DEPLOY_ID as inactive..."
            gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "/repos/${{ github.repository }}/deployments/$DEPLOY_ID/statuses" \
              -f state='inactive' \
              -f description='Superseded by newer deployment' \
              > /dev/null 2>&1 || echo "::warning::Could not mark deployment $DEPLOY_ID as inactive"
          done
          echo "✓ Previous deployments marked as inactive"
        else
          echo "No previous deployments to mark as inactive"
        fi

        echo "::endgroup::"

    - name: Create deployment status
      id: create-status
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        echo "::group::Creating deployment status"

        DEPLOYMENT_ID="${{ steps.create-deployment.outputs.deployment_id }}"

        # Build the API call
        API_CALL="gh api --method POST \
          -H \"Accept: application/vnd.github+json\" \
          -H \"X-GitHub-Api-Version: 2022-11-28\" \
          /repos/${{ github.repository }}/deployments/$DEPLOYMENT_ID/statuses \
          -f state='${{ inputs.state }}'"

        # Add environment URL if provided
        if [ -n "${{ inputs.deployment_url }}" ]; then
          API_CALL="$API_CALL -f environment_url='${{ inputs.deployment_url }}'"
        fi

        # Add description if provided
        if [ -n "${{ inputs.description }}" ]; then
          API_CALL="$API_CALL -f description='${{ inputs.description }}'"
        else
          # Default descriptions based on state
          case "${{ inputs.state }}" in
            pending)
              API_CALL="$API_CALL -f description='Deployment pending'"
              ;;
            in_progress)
              API_CALL="$API_CALL -f description='Deployment in progress'"
              ;;
            success)
              API_CALL="$API_CALL -f description='Deployment successful'"
              ;;
            failure)
              API_CALL="$API_CALL -f description='Deployment failed'"
              ;;
            error)
              API_CALL="$API_CALL -f description='Deployment error'"
              ;;
            inactive)
              API_CALL="$API_CALL -f description='Deployment inactive'"
              ;;
          esac
        fi

        # Execute the API call
        STATUS_ID=$(eval "$API_CALL" --jq '.id')

        echo "status_id=$STATUS_ID" >> $GITHUB_OUTPUT
        echo "✓ Created deployment status ID: $STATUS_ID"
        echo "  State: ${{ inputs.state }}"
        if [ -n "${{ inputs.deployment_url }}" ]; then
          echo "  URL: ${{ inputs.deployment_url }}"
        fi

        echo "::endgroup::"

    - name: Deployment status summary
      shell: bash
      run: |
        echo "::group::Deployment Status Summary"
        echo "✓ GitHub Deployment updated"
        echo "  Deployment ID: ${{ steps.create-deployment.outputs.deployment_id }}"
        echo "  Status ID: ${{ steps.create-status.outputs.status_id }}"
        echo "  Environment: ${{ inputs.environment }}"
        echo "  State: ${{ inputs.state }}"
        if [ -n "${{ inputs.deployment_url }}" ]; then
          echo "  URL: ${{ inputs.deployment_url }}"
        fi
        echo "::endgroup::"
